name: Deno
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test on Deno ${{ matrix.deno-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deno-version: [v1.x, v2.x]
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run tests
        run: deno test --allow-net test/deno/*.js
